/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

module counter(reset, clk, wdata, wr, data);
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  input clk;
  wire clk;
  output [7:0] data;
  reg [7:0] data;
  input reset;
  wire reset;
  input [7:0] wdata;
  wire [7:0] wdata;
  input wr;
  wire wr;
  sky130_fd_sc_hd__nand2_1 _62_ (
    .A(_53_),
    .B(_61_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__o21ai_0 _63_ (
    .A1(_25_),
    .A2(_61_),
    .B1(_33_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _64_ (
    .A(_25_),
    .B(_26_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__xnor2_1 _65_ (
    .A(_25_),
    .B(_26_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nand2_1 _66_ (
    .A(_61_),
    .B(_54_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__o21ai_0 _67_ (
    .A1(_61_),
    .A2(_35_),
    .B1(_36_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _68_ (
    .A(_27_),
    .B(_34_),
    .X(_37_)
  );
  sky130_fd_sc_hd__nand2_1 _69_ (
    .A(_61_),
    .B(_55_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__o21ai_0 _70_ (
    .A1(_61_),
    .A2(_37_),
    .B1(_38_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a31oi_1 _71_ (
    .A1(_25_),
    .A2(_26_),
    .A3(_27_),
    .B1(_28_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__and4_1 _72_ (
    .A(_25_),
    .B(_26_),
    .C(_27_),
    .D(_28_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nand2_1 _73_ (
    .A(_61_),
    .B(_56_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__o31ai_1 _74_ (
    .A1(_61_),
    .A2(_39_),
    .A3(_40_),
    .B1(_41_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nand2_1 _75_ (
    .A(_29_),
    .B(_40_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__xnor2_1 _76_ (
    .A(_29_),
    .B(_40_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__nand2_1 _77_ (
    .A(_61_),
    .B(_57_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__o21ai_0 _78_ (
    .A1(_61_),
    .A2(_43_),
    .B1(_44_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__xor2_1 _79_ (
    .A(_30_),
    .B(_42_),
    .X(_45_)
  );
  sky130_fd_sc_hd__nand2_1 _80_ (
    .A(_61_),
    .B(_58_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__o21ai_0 _81_ (
    .A1(_61_),
    .A2(_45_),
    .B1(_46_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a31o_1 _82_ (
    .A1(_29_),
    .A2(_30_),
    .A3(_40_),
    .B1(_31_),
    .X(_47_)
  );
  sky130_fd_sc_hd__nand4_1 _83_ (
    .A(_29_),
    .B(_30_),
    .C(_31_),
    .D(_40_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__nand2_1 _84_ (
    .A(_47_),
    .B(_48_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__nand2_1 _85_ (
    .A(_61_),
    .B(_59_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__o21ai_0 _86_ (
    .A1(_61_),
    .A2(_49_),
    .B1(_50_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xor2_1 _87_ (
    .A(_32_),
    .B(_48_),
    .X(_51_)
  );
  sky130_fd_sc_hd__nand2_1 _88_ (
    .A(_61_),
    .B(_60_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__o21ai_0 _89_ (
    .A1(_61_),
    .A2(_51_),
    .B1(_52_),
    .Y(_24_)
  );
  always @(posedge clk, posedge reset)
    if (reset) data[0] <= 1'h0;
    else data[0] <= _00_[0];
  always @(posedge clk, posedge reset)
    if (reset) data[1] <= 1'h0;
    else data[1] <= _00_[1];
  always @(posedge clk, posedge reset)
    if (reset) data[2] <= 1'h0;
    else data[2] <= _00_[2];
  always @(posedge clk, posedge reset)
    if (reset) data[3] <= 1'h0;
    else data[3] <= _00_[3];
  always @(posedge clk, posedge reset)
    if (reset) data[4] <= 1'h0;
    else data[4] <= _00_[4];
  always @(posedge clk, posedge reset)
    if (reset) data[5] <= 1'h0;
    else data[5] <= _00_[5];
  always @(posedge clk, posedge reset)
    if (reset) data[6] <= 1'h0;
    else data[6] <= _00_[6];
  always @(posedge clk, posedge reset)
    if (reset) data[7] <= 1'h0;
    else data[7] <= _00_[7];
  assign _25_ = data[0];
  assign _53_ = wdata[0];
  assign _61_ = wr;
  assign _00_[0] = _17_;
  assign _26_ = data[1];
  assign _54_ = wdata[1];
  assign _00_[1] = _18_;
  assign _27_ = data[2];
  assign _55_ = wdata[2];
  assign _00_[2] = _19_;
  assign _28_ = data[3];
  assign _56_ = wdata[3];
  assign _00_[3] = _20_;
  assign _29_ = data[4];
  assign _57_ = wdata[4];
  assign _00_[4] = _21_;
  assign _30_ = data[5];
  assign _58_ = wdata[5];
  assign _00_[5] = _22_;
  assign _31_ = data[6];
  assign _59_ = wdata[6];
  assign _00_[6] = _23_;
  assign _32_ = data[7];
  assign _60_ = wdata[7];
  assign _00_[7] = _24_;
endmodule
