#!/bin/sh
# Компиллируем и стартуем симуляцию
clear
echo СБОРКА ДЛЯ СИМУЛЯЦИИ
iverilog -o qqq counter.v tcounter.v

echo симуляция iVerilog VVP
# Можно просто запустить файл *ggg
vvp qqq

echo симуляция GTKWAVE 
gtkwave --start=100 out.vcd

echo
echo ---END---
read a
